require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JewelsController do

  # This should return the minimal set of attributes required to create a valid
  # Jewel. As you add validations to Jewel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JewelsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all jewels as @jewels" do
      jewel = Jewel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:jewels).should eq([jewel])
    end
  end

  describe "GET show" do
    it "assigns the requested jewel as @jewel" do
      jewel = Jewel.create! valid_attributes
      get :show, {:id => jewel.to_param}, valid_session
      assigns(:jewel).should eq(jewel)
    end
  end

  describe "GET new" do
    it "assigns a new jewel as @jewel" do
      get :new, {}, valid_session
      assigns(:jewel).should be_a_new(Jewel)
    end
  end

  describe "GET edit" do
    it "assigns the requested jewel as @jewel" do
      jewel = Jewel.create! valid_attributes
      get :edit, {:id => jewel.to_param}, valid_session
      assigns(:jewel).should eq(jewel)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Jewel" do
        expect {
          post :create, {:jewel => valid_attributes}, valid_session
        }.to change(Jewel, :count).by(1)
      end

      it "assigns a newly created jewel as @jewel" do
        post :create, {:jewel => valid_attributes}, valid_session
        assigns(:jewel).should be_a(Jewel)
        assigns(:jewel).should be_persisted
      end

      it "redirects to the created jewel" do
        post :create, {:jewel => valid_attributes}, valid_session
        response.should redirect_to(Jewel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved jewel as @jewel" do
        # Trigger the behavior that occurs when invalid params are submitted
        Jewel.any_instance.stub(:save).and_return(false)
        post :create, {:jewel => {  }}, valid_session
        assigns(:jewel).should be_a_new(Jewel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Jewel.any_instance.stub(:save).and_return(false)
        post :create, {:jewel => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested jewel" do
        jewel = Jewel.create! valid_attributes
        # Assuming there are no other jewels in the database, this
        # specifies that the Jewel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Jewel.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => jewel.to_param, :jewel => { "these" => "params" }}, valid_session
      end

      it "assigns the requested jewel as @jewel" do
        jewel = Jewel.create! valid_attributes
        put :update, {:id => jewel.to_param, :jewel => valid_attributes}, valid_session
        assigns(:jewel).should eq(jewel)
      end

      it "redirects to the jewel" do
        jewel = Jewel.create! valid_attributes
        put :update, {:id => jewel.to_param, :jewel => valid_attributes}, valid_session
        response.should redirect_to(jewel)
      end
    end

    describe "with invalid params" do
      it "assigns the jewel as @jewel" do
        jewel = Jewel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Jewel.any_instance.stub(:save).and_return(false)
        put :update, {:id => jewel.to_param, :jewel => {  }}, valid_session
        assigns(:jewel).should eq(jewel)
      end

      it "re-renders the 'edit' template" do
        jewel = Jewel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Jewel.any_instance.stub(:save).and_return(false)
        put :update, {:id => jewel.to_param, :jewel => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested jewel" do
      jewel = Jewel.create! valid_attributes
      expect {
        delete :destroy, {:id => jewel.to_param}, valid_session
      }.to change(Jewel, :count).by(-1)
    end

    it "redirects to the jewels list" do
      jewel = Jewel.create! valid_attributes
      delete :destroy, {:id => jewel.to_param}, valid_session
      response.should redirect_to(jewels_url)
    end
  end

end
